"""Prompt exports for the research agent."""

from .system_prompt import BOOTSTRAP_SYSTEM_PROMPT
from .task_prompts import (
    MACRO_PLAN_DESIGN_PROMPT,
    SIMILAR_EXP_SEARCH_PROMPT,
    STAGE_DESIGN_PROMPT,
    SURVEY_EXPANSION_PROMPT,
    SURVEY_QUERY_GENERATE_PROMPT,
    SURVEY_REPORT_GENERATE_PROMPT,
)

__all__ = [
    "BOOTSTRAP_SYSTEM_PROMPT",
    "SURVEY_QUERY_GENERATE_PROMPT",
    "SURVEY_EXPANSION_PROMPT",
    "SIMILAR_EXP_SEARCH_PROMPT",
    "SURVEY_REPORT_GENERATE_PROMPT",
    "STAGE_DESIGN_PROMPT",
    "MACRO_PLAN_DESIGN_PROMPT",
]
